# Generated by Django 6.0.5 on 2026-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_gameweek_match_seasonteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
