# Generated by Django 6.0.5 on 2026-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_create_competitions',
            field=models.BooleanField(default=False),
        ),
    ]
