# Generated by Django 6.0.5 on 2026-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'difficulty', 'name']},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='visibility',
            new_name='discovery',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('COMPETITION', 'Competition'), ('PICKS', 'Picks'), ('JOKER', 'Joker'), ('COLLECTION', 'Collection'), ('EXPLORATION', 'Exploration'), ('SPECIAL', 'Special')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='difficulty',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('LEGENDARY', 'Legendary')], default='BRONZE', max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon name used in the UI.', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tracking_start',
            field=models.DateTimeField(blank=True, help_text='Only activity on or after this date counts towards this achievement.', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
