# Generated by Django 6.0.5 on 2026-07-05 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at', 'achievement__name']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='target',
            field=models.PositiveIntegerField(default=1, help_text='Progress required to unlock this achievement.'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
