# Generated by Django 6.0.5 on 2026-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_userachievement_options_achievement_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['display_order', 'category', 'difficulty', 'name']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='display_order',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
