# Generated by Django 6.0.5 on 2026-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_options_achievement_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='notification_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
