# Generated by Django 6.0.5 on 2026-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
