# Generated by Django 6.0.5 on 2026-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_joker',
            field=models.BooleanField(default=True),
        ),
    ]
