# Generated by Django 6.0.5 on 2026-06-11 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_allow_joker'),
        ('fixtures', '0004_alter_gameweek_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionGameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_gameweeks', to='competitions.competition')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_gameweeks', to='fixtures.gameweek')),
            ],
            options={
                'ordering': ['gameweek__number'],
                'unique_together': {('competition', 'gameweek')},
            },
        ),
    ]
