# Generated by Django 6.0.5 on 2026-06-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competitiongameweek'),
        ('fixtures', '0004_alter_gameweek_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiongameweek',
            options={'ordering': ['competition_week_number']},
        ),
        migrations.AlterUniqueTogether(
            name='competitiongameweek',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitiongameweek',
            name='competition_week_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='competitiongameweek',
            constraint=models.UniqueConstraint(fields=('competition', 'gameweek'), name='unique_gameweek_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='competitiongameweek',
            constraint=models.UniqueConstraint(fields=('competition', 'competition_week_number'), name='unique_week_number_per_competition'),
        ),
    ]
