# Generated by Django 6.0.5 on 2026-06-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competitiongameweek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmember',
            name='eliminated_in_competition_gameweek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminated_members', to='competitions.competitiongameweek'),
        ),
    ]
