# Generated by Django 6.0.5 on 2026-06-28 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competitionmember_eliminated_in_competition_gameweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='has_multiple_winners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetitionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='competitions.competition')),
                ('competition_gameweek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='competitions.competitiongameweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
