# Generated by Django 6.0.5 on 2026-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('VOID', 'No Winner')], default='ACTIVE', max_length=20),
        ),
    ]
