# Generated by Django 6.0.5 on 2026-06-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_competition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='winning_competition_gameweek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_competitions', to='competitions.competitiongameweek'),
        ),
    ]
