# Generated by Django 6.0.5 on 2026-06-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0004_competitiongameweek'),
        ('fixtures', '0004_alter_gameweek_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joker', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSE', 'Lose'), ('DRAW_ELIMINATED', 'Draw - eliminated'), ('DRAW_SAFE', 'Draw - joker safe')], default='PENDING', max_length=30)),
                ('processed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('competition_gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='competitions.competitiongameweek')),
                ('competition_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='competitions.competitionmember')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='fixtures.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='fixtures.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competition_member', 'competition_gameweek'), name='unique_selection_per_member_competition_gameweek'), models.UniqueConstraint(fields=('competition_member', 'team'), name='unique_team_per_member_competition')],
            },
        ),
    ]
